### PR TITLE
Judging page fixes

### LINKED ISSUE #12: Channels Layers
We need the judging screens to receive the updated time/score from the server even from updates from other judges. At a glance, Django Channels Layers seem to be a good way to do this.

Right now the websocket is purely between the one instance of the judging page and the server. It won't see any responses from the server initiated by another judge. 

@lpulley Looks like we may need to install redis. Are you familiar with it at all?

### PR DESCRIPTION
**Pull request by mgale456**
The features of the judging page are complete. The Scoring branch has also been rolled into this. Please test it, and recommend other things to add. The beautification is definitely not done, and if someone else wants to give that a shot, that'd be great. 

It handles everything that the old one did afaik, and functions very similarly. 

Non-exhaustive list of features:

1. Easy to add new buttons to the page by using the Django admin site
1. Supports any number of teams
2. Scoring supports changing the multiplier in the middle of the match, and preserving the multiplier on previous points earned
3. The counter arrows also support typing for input to the db (the multiplier for these is scored based on the multiplier at the time of the last update)
4. The delete buttons at the bottom do not actually delete the db row. They just change a boolean
5. Inputs are blocked from sending to the db if a team is not selected, the game hasn't been started, or the game is already finalized
1. Supports non-linear scoring (like Brewing Potions). Last year we would have needed 3 buttons just for that.
6. It has all the features of the old one

### CODE REVIEW

**Comment by lpulley** [comment]
Trying to test this but I can't seem to find how to select a team?

**Comment by mgale456** [comment]
Click a team name at the top of the page. We can improve the clarity with
some css. Right now the chosen team is Bolded.

**Comment by lpulley** [comment]
Sorry I've been so absent on this!!!! I'm testing this now and will approve when done.

**Review by lpulley — APPROVED** [review]
Looks great!

**Review by denniszaslavsky — APPROVED** [review]

**Pull request merged**
